#!/bin/bash

README="/home/cyber/Desktop/README.html"

while true
do
  if ( eval ufw status | grep active ); then
    if ( eval sed -n 25p $README | grep '❌' ); then
      sed -i '25s/❌/✅/' $README
    fi
  fi
  if ( eval cat /etc/login.defs | grep PASS_MAX_DAYS | grep 90 ); then
    if ( eval sed -n 32p $README | grep '❌' ); then
      sed -i '32s/❌/✅/' $README
    fi
  fi
  if ( eval cat /etc/login.defs | grep PASS_MIN_DAYS | grep 10 ); then
    if ( eval sed -n 35p $README | grep '❌' ); then
      sed -i '35s/❌/✅/' $README
    fi
  fi
  if ( eval cat /etc/group | grep kali ); then
    if ( eval sed -n 39p $README | grep '❌' ); then
      sed -i '39s/❌/✅/' $README
    fi
  fi
  if ( eval dpkg -l | grep openssh-client ); then
    if ( eval sed -n 43p $README | grep '❌' ); then
      sed -i '43s/❌/✅/' $README
    fi
  fi
  if ( ! eval cat /etc/ssh/ssh_config | grep 'ForwardX11 no' | grep \# ); then
    if ( eval sed -n 46p $README | grep '❌' ); then
      sed -i '46s/❌/✅/' $README
    fi
  fi
  if ( ! eval cat /etc/ssh/ssh_config | grep 'Port 22' | grep \# ); then
    if ( eval sed -n 49p $README | grep '❌' ); then
      sed -i '49s/❌/✅/' $README
    fi
  fi
  if ( eval cat /etc/ssh/ssh_config | grep 'Protocol 2' ); then
    if ( eval sed -n 52p $README | grep '❌' ); then
      sed -i '52s/❌/✅/' $README
    fi
  fi
  if ( eval cat /etc/ssh/ssh_config | grep 'PermitRootLogin no' ); then
    if ( eval sed -n 55p $README | grep '❌' ); then
      sed -i '55s/❌/✅/' $README
    fi
  fi
done
